name: Beta Test Build

on:
  push:
    branches:
      - BETA

jobs:
  beta-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: python build_pyinstaller.py

    - name: UPX Compress Executable
      run: |
        $exePath = "dist/ExamSplitter/ExamSplitter.exe"
        if (Test-Path $exePath) {
          $originalSize = (Get-Item $exePath).Length / 1MB
          Write-Host "Original exe size: $([math]::Round($originalSize,2)) MB"
          try {
            choco install upx -y
            upx --best --lzma $exePath
            $compressedSize = (Get-Item $exePath).Length / 1MB
            Write-Host "UPX compressed size: $([math]::Round($compressedSize,2)) MB"
          } catch {
            Write-Host "UPX compression skipped (UPX not available)"
          }
        } else {
          Write-Host "ExamSplitter.exe not found, skipping UPX"
        }

    - name: Verify executable
      run: |
        if (Test-Path "dist/ExamSplitter/ExamSplitter.exe") {
          Write-Host "Build successful - ExamSplitter.exe created"
          $folderSize = (Get-ChildItem "dist/ExamSplitter" -Recurse | Measure-Object -Property Length -Sum).Sum / 1MB
          Write-Host "Folder size: $([math]::Round($folderSize, 2)) MB"
        } else {
          Write-Host "Build failed - ExamSplitter.exe not found"
          exit 1
        }
        
    - name: Create beta package
      run: |
        mkdir "ExamSplitter-Beta"
        if (Test-Path "dist/ExamSplitter") {
          Copy-Item -Path "dist/ExamSplitter" -Destination "ExamSplitter-Beta/ExamSplitter" -Recurse -Force
        } else {
          Write-Host "Error: ExamSplitter folder not found"
          exit 1
        }
        Copy-Item README.md "ExamSplitter-Beta/" -Force
        Copy-Item LICENSE "ExamSplitter-Beta/" -Force
        Compress-Archive -Path "ExamSplitter-Beta/*" -DestinationPath "ExamSplitter-Beta.zip" -Force
        Remove-Item -Recurse -Force "ExamSplitter-Beta"
        Write-Host "Beta package created: ExamSplitter-Beta.zip"
        
    - name: Upload beta build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExamSplitter-BetaBuild
        path: ExamSplitter-Beta.zip
        
    - name: Build Summary
      if: github.event_name == 'push'
      run: |
        $folderSize = (Get-ChildItem "dist/ExamSplitter" -Recurse | Measure-Object -Property Length -Sum).Sum / 1MB
        echo "## Beta 테스트 빌드 완료" >> $env:GITHUB_STEP_SUMMARY
        echo "**빌드 성공**" >> $env:GITHUB_STEP_SUMMARY
        echo "**폴더 크기**: $([math]::Round($folderSize, 2)) MB" >> $env:GITHUB_STEP_SUMMARY
        echo "**다운로드**: Actions 탭의 Artifacts에서 다운로드 가능" >> $env:GITHUB_STEP_SUMMARY
